### ISSUE TITLE
Python version and venv suggestion for dev?

### ISSUE THREAD

**Issue by sariths** [pollination/queenbee-python-dsl#17]
@mostaphaRoudsari It might be worthwhile to mention that Python version>=3.7 is required in the readme page itself. I know several people (including myself :) ) are using 3.6 . 
Secondly, and related to above, is it preferable to use a dedicated venv just to avoid conflicts?

**Comment by mostaphaRoudsari** [comment]
Hi @sariths, will add the Python version.

In my opinion, `venv` is optional and up to the user. You can use it if you like. :)
