### ISSUE TITLE
queenbee_dsl\package.py is missing the function write

### ISSUE THREAD

**Issue by sariths** [pollination/queenbee-python-dsl#18]
@mostaphaRoudsari, The write method shown in the example does not exist in https://github.com/pollination/queenbee-python-dsl/blob/master/queenbee_dsl/package.py, thus giving an Import Error. Is `write` supposed to be `translate` https://github.com/pollination/queenbee-python-dsl/blob/master/queenbee_dsl/package.py#L228-L256?

![image](https://user-images.githubusercontent.com/10361848/104457774-c1411000-55aa-11eb-8b6b-0660e7355d68.png)

**Comment by mostaphaRoudsari** [comment]
Good catch! I changed the name but forgot to update the documentation. Will fix it!
